# Generated by Django 3.2 on 2024-11-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DRIVER', 'DRIVER'), ('SUPER_ADMIN', 'SUPER_ADMIN')], default='DRIVER', max_length=100),
        ),
    ]
