# Generated by Django 3.2 on 2024-11-05 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('id_type', models.CharField(choices=[('PASSPORT', 'PASSPORT'), ('LICENSE', 'LICENSE'), ('VOTERS_CARD', 'VOTERS_CARD'), ('NATIONAL_ID', 'NATIONAL_ID')], default='PASSPORT', max_length=100)),
                ('vehicle_reg_no', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=10, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('verificaton_status', models.CharField(choices=[('VERIFIED', 'VERIFIED'), ('UNVERIFIED', 'UNVERIFIED'), ('PROCESSING', 'PROCESSING')], default='PROCESSING', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=255, unique=True)),
                ('license_plate', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('MAINTENANCE', 'MAINTENANCE')], default='ACTIVE', max_length=40)),
                ('model', models.CharField(max_length=255)),
                ('year_of_onboarding', models.DateField(auto_now_add=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='truck.driver')),
            ],
        ),
    ]
