# Generated by Django 3.2 on 2025-01-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0002_auto_20250115_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Truck capacity in tons', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='truck_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
