# Generated by Django 3.2 on 2025-01-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to_truck',
            new_name='assigned_to',
        ),
    ]
