# Generated by Django 3.2 on 2025-02-21 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('truck', '0003_auto_20250118_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_id', models.CharField(max_length=20, unique=True)),
                ('maintenance_type', models.CharField(choices=[('FULL_MAINTENANCE', 'FULL_MAINTENANCE'), ('PART_MAINTENANCE', 'PART_MAINTENANCE'), ('OTHER', 'OTHER')], default='OTHER', max_length=40)),
                ('maintenance_status', models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('DONE', 'DONE'), ('OTHER', 'OTHER')], default='OTHER', max_length=40)),
                ('scheduled_date', models.DateField()),
                ('truck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.truck')),
            ],
        ),
    ]
